import { useState } from "react";
import { MessageSquare, Stethoscope, User } from "lucide-react";

export default function ExplanationPanel({ explanation, explaining, onExplain }) {
    const [audience, setAudience] = useState("patient");

    const switchAudience = (a) => {
        setAudience(a);
        onExplain(a);
    };

    return (
        <div className="explanation-panel glass-card animate-in">
            <div className="panel-header">
                <MessageSquare size={18} className="icon-accent" />
                <h2>AI Explanation</h2>
            </div>

            <div className="audience-tabs">
                <button
                    className={`tab ${audience === "patient" ? "active" : ""}`}
                    onClick={() => switchAudience("patient")}
                >
                    <User size={13} /> For Patient
                </button>
                <button
                    className={`tab ${audience === "clinician" ? "active" : ""}`}
                    onClick={() => switchAudience("clinician")}
                >
                    <Stethoscope size={13} /> For Clinician
                </button>
            </div>

            <div className="explanation-body">
                {explaining && !explanation && (
                    <div className="typing-indicator">
                        <span /><span /><span />
                    </div>
                )}
                {explanation && (
                    <p className="explanation-text">
                        {explanation}
                        {explaining && <span className="cursor-blink">|</span>}
                    </p>
                )}
                {!explanation && !explaining && (
                    <p className="placeholder-text">
                        Press "Explain to Patient" or "Clinician View" in the Diagnosis card to generate an AI explanation.
                    </p>
                )}
            </div>

            {explanation && (
                <div className="gemini-badge">
                    <span>✨ Generated by Gemini Flash</span>
                </div>
            )}
        </div>
    );
}
